//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAP_VIRTUAL.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAP_VIRTUAL.Resources.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Item.
        /// </summary>
        internal static string addToolStripMenuItem {
            get {
                return ResourceManager.GetString("addToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string closeToolStripMenuItem {
            get {
                return ResourceManager.GetString("closeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string editToolStripMenuItem {
            get {
                return ResourceManager.GetString("editToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string exitToolStripMenuItem {
            get {
                return ResourceManager.GetString("exitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        internal static string fileToolStripMenuItem {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string helpToolStripMenuItem {
            get {
                return ResourceManager.GetString("helpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KR_neu {
            get {
                object obj = ResourceManager.GetObject("KR_neu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have added item!.
        /// </summary>
        internal static string msgAdd {
            get {
                return ResourceManager.GetString("msgAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to add item!.
        /// </summary>
        internal static string msgAddError {
            get {
                return ResourceManager.GetString("msgAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a have been closing!.
        /// </summary>
        internal static string msgClose {
            get {
                return ResourceManager.GetString("msgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to close file!.
        /// </summary>
        internal static string msgCloseError {
            get {
                return ResourceManager.GetString("msgCloseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to access Help file!.
        /// </summary>
        internal static string msgHelpError {
            get {
                return ResourceManager.GetString("msgHelpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a have been creating!.
        /// </summary>
        internal static string msgNew {
            get {
                return ResourceManager.GetString("msgNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to create file!.
        /// </summary>
        internal static string msgNewError {
            get {
                return ResourceManager.GetString("msgNewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a have been opening!.
        /// </summary>
        internal static string msgOpen {
            get {
                return ResourceManager.GetString("msgOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to open file!.
        /// </summary>
        internal static string msgOpenError {
            get {
                return ResourceManager.GetString("msgOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a have been printing!.
        /// </summary>
        internal static string msgPrint {
            get {
                return ResourceManager.GetString("msgPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to print file!.
        /// </summary>
        internal static string msgPrintError {
            get {
                return ResourceManager.GetString("msgPrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have removed item!.
        /// </summary>
        internal static string msgRemove {
            get {
                return ResourceManager.GetString("msgRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to remove item!.
        /// </summary>
        internal static string msgRemoveError {
            get {
                return ResourceManager.GetString("msgRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have been saving.
        /// </summary>
        internal static string msgSave {
            get {
                return ResourceManager.GetString("msgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have been saving as.
        /// </summary>
        internal static string msgSaveAs {
            get {
                return ResourceManager.GetString("msgSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to save file!.
        /// </summary>
        internal static string msgSaveAsError {
            get {
                return ResourceManager.GetString("msgSaveAsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to save file!.
        /// </summary>
        internal static string msgSaveError {
            get {
                return ResourceManager.GetString("msgSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to edit settings!.
        /// </summary>
        internal static string msgSettingsError {
            get {
                return ResourceManager.GetString("msgSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        internal static string newToolStripMenuItem {
            get {
                return ResourceManager.GetString("newToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        internal static string openToolStripMenuItem {
            get {
                return ResourceManager.GetString("openToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print.
        /// </summary>
        internal static string printToolStripMenuItem {
            get {
                return ResourceManager.GetString("printToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Item.
        /// </summary>
        internal static string removeToolStripMenuItem {
            get {
                return ResourceManager.GetString("removeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save As.
        /// </summary>
        internal static string saveAsToolStripMenuItem {
            get {
                return ResourceManager.GetString("saveAsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string saveToolStripMenuItem {
            get {
                return ResourceManager.GetString("saveToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string settingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("settingsToolStripMenuItem", resourceCulture);
            }
        }
    }
}
